# Generated by Django 5.2.17 on 2026-09-21 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='color',
            field=models.CharField(default='#3b82f6', help_text='Hex accent color, e.g. #3b82f6.', max_length=7, validators=[django.core.validators.RegexValidator(message='کد رنگ باید یک مقدار هگز معتبر مانند #3b82f6 باشد.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
    ]
